version: "3.8"

services:
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    restart: unless-stopped
    hostname: wg-easy
    environment:
      - WG_HOST: ${WG_HOST:-}
      - PASSWORD: ${PASSWORD:-}
    networks:
      - wg-easy
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  pihole:
    image: pihole/pihole
    container_name: pihole
    environment:
      - WEBPASSWORD: ${WEBPASSWORD:-}
    networks:
      - wg-easy
    volumes:
      - '~/.pihole/etc-pihole:/etc/pihole'
      - './.pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    networks:
      - wg-easy
    ports:
      - 80:80
      - 443:443
    environment:
      - WG_HOST: ${WG_HOST:-}
      - PIHOLE_HOST: ${PIHOLE_HOST:-}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  wg-easy:

volumes:
  caddy_data:
  caddy_config:
